version: "2.3"
services:
  whisper:
    build: .
    restart: always
    tty: true
    ports:
      - "10010:8080"
    volumes:
      - .:/app
    runtime: nvidia
    command:
      [
        "gunicorn",
        "--bind",
        ":8080",
        "--workers",
        "3",
        "--timeout",
        "300",
        "main:app",
      ]
